Update action.yml
nrwl/last-successful-commit-action pull request #2
Opened 2022-10-11 19:58 UTC by yakirm-cr

Upgrade from `node12` to `node16` (due to deprecation warning in a workflow's summary):

![image](https://user-images.githubusercontent.com/86773995/195186731-87fe8fb4-5736-47ef-9396-6fe53217c176.png)

2022-11-16 09:50 UTC, hylle requested changes
You should also add your changes to the `package.json` and lock-file. 
Without it the action will revert back to a deprecated `set-output` the next time someone builds the action.

2022-11-17 06:33 UTC, yakirm-cr commented
> You should also add your changes to the `package.json` and lock-file. Without it the action will revert back to a deprecated `set-output` the next time someone builds the action.

@hylle Thanks for the comment.
The `package.json` and `package-lock.json` files were updated.

2022-11-17 08:55 UTC, hylle approved these changes

2022-11-17 09:24 UTC, yakirm-cr commented
@hylle Thanks for the approval.
After checking [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) there is no `setOutput` command and it seems that the change in the PR is breaking this action - the commit hash is NOT set in the output of the action. :slightly_frowning_face:

2022-11-17 09:34 UTC, hylle commented
> After checking [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) there is no `setOutput` command and it seems that the change in the PR is breaking this action - the commit hash is NOT set in the output of the action. 🙁

I've done this to a couple of actions that we use in our org. `setOutput` definitely still exists in `@actions/core`.
The doc you linked also specifically says you just need to upgrade `@actions/core` to `1.10.0` or later.

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

@yakirm-cr Could you try running `npm run build` again, to see if you not missing something in the dist?

2022-11-17 09:49 UTC, yakirm-cr commented
> > After checking [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) there is no `setOutput` command and it seems that the change in the PR is breaking this action - the commit hash is NOT set in the output of the action. slightly_frowning_face
> 
> I've done this to a couple of actions that we use in our org. `setOutput` definitely still exists in `@actions/core`. The doc you linked also specifically says you just need to upgrade `@actions/core` to `1.10.0` or later.
> 
> > Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.
> 
> @yakirm-cr Could you try running `npm run build` again, to see if you not missing something in the dist?

@hylle You are right. :slightly_smiling_face: 
I missed the update of the `dist` dir.
Everything is now working with the changes in the `dist` dir.
Thanks!

I am proceeding with merging this PR.

2022-11-17 09:51 UTC, hylle commented
I think you probably need someone from nrwl to do that. 🙂 

Just going to tag the original author and hope he sees, since it seems like this repo might not be too actively monitored by nrwl. @rarmatei

nrwl might want to make dist/build themselves, not sure what their policy is. 🙂

2022-11-17 10:31 UTC, meeroslav commented
Hey folks, this action has been deprecated in favor of https://github.com/nrwl/nx-set-shas.
Version 1.x of `nx-set-shas` has equal behavior like this action, but we suggest using the latest solution as it provides better ergonomics and logic.

There will be no further development on this repo.
Sorry for the inconvenience.

2022-11-17 10:45 UTC, yakirm-cr commented
Thanks for info, @meeroslav.
I recommend to update the README.md with your comments above and then archive this repo.

2022-11-17 10:45 UTC, closed without merging